### ISSUE TITLE
Duplicate values in didUpdatePositionEstimate delegate method

### ISSUE THREAD

**Issue by jim-martin** [mapbox/mapbox-vision-ios#55] opened 2019-02-21 19:46 UTC
When logging the output of the `didUpdateEstimatedPosition` Delegate method, it looks like there's an issue with the data.

The `Position` object contains duplicate longitude values, rather than a lat/lon pair:

```
Optional(__C.CLLocationCoordinate2D(latitude: -122.39877355235566, longitude: -122.39877355235566))
Optional(__C.CLLocationCoordinate2D(latitude: -122.39876948750845, longitude: -122.39876948750845))
Optional(__C.CLLocationCoordinate2D(latitude: -122.39876596806609, longitude: -122.39876596806609))
```
This is true for both `CLLocation`, and `CVAPosition`.

cc @avi-c, @atripathi-mb

**Comment by atripathi-mb** [comment] 2019-02-21 20:59
cc @deniskoronchik @torypaulsmith

**Comment by chezzdev** [comment] 2019-02-22 10:59
@jim-martin @atripathi-mb thanks for the report. We've found the root cause and will update the SDK with a fix.

**Comment by avi-c** [comment] 2019-02-28 14:29
@chezzdev - is there a way for us to pick up just this fix on the branch of vision core that we are already using? It would be great to address this issue even while we wait for the larger switch to Vision Beta.

**Comment by avi-c** [comment] 2019-03-04 19:16
Version 0.2.1 of MapboxVisionCore was merged to address the duplicate coordinate issue. I'm closing this ticket now that we receive the position updates. We can write further tickets as we use the newly delivered data.

**Closed by avi-c** 2019-03-04 19:16 UTC
